#!/bin/sh

case "$REQUEST_METHOD" in 
    GET)
    if test -z "$QUERY_STRING" ; then
cat << EOF
Content-type: text/xml

<?xml version="1.0" ?>
<environment>
 <SERVER_NAME>$SERVER_NAME</SERVER_NAME>
 <SERVER_SOFTWARE>$SERVER_SOFTWARE</SERVER_SOFTWARE>
 <SERVER_PROTOCOL>$SERVER_PROTOCOL</SERVER_PROTOCOL>
 <SERVER_PORT>$SERVER_PORT</SERVER_PORT>
 <SERVER_SIGNATURE>$SERVER_SIGNATURE</SERVER_SIGNATURE>
 <REMOTE_ADDR>$REMOTE_ADDR</REMOTE_ADDR>
 <REMOTE_HOST>$REMOTE_HOST</REMOTE_HOST>
 <REMOTE_PORT>$REMOTE_PORT</REMOTE_PORT>
 <HTTP_USER_AGENT>$HTTP_USER_AGENT</HTTP_USER_AGENT>
 <HTTP_REFFERER>$HTTP_REFFERER</HTTP_REFFERER>
 <HTTP_REQUEST>$HTTP_REQUEST</HTTP_REQUEST>
 <DOCUMENT_ROOT>$DOCUMENT_ROOT</DOCUMENT_ROOT>
 <REQUEST_TIME>$REQUEST_TIME</REQUEST_TIME>
</environment>
EOF
    else
	   URL=`/usr/local/bin/unescape $QUERY_STRING`
      wget "$URL" -q -O /tmp/wget$$ >/tmp/wg
	   echo "Content-type: text/xml"
	   echo
	   cat /tmp/wget$$
	   rm  /tmp/wget$$
    fi
	;;
esac
